name: nix nario restore
description: Restore the nix store to the actions cache using nix nario

inputs:
  path:
    description: "nix path to save to the cache"
    required: false

outputs:
  cache-hit:
    description: "whether the cache was hit"
    value: ${{ steps.pkg.outputs.exists || steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - id: env
      shell: bash
      run: |
        # Setup env

        TMPNIX="/nix/_tmp"
        if sudo mkdir -p "${TMPNIX}"; then
          sudo chmod 1777 "${TMPNIX}"
          echo "tmp=${TMPNIX}" >> $GITHUB_OUTPUT
        else
          TMPNIX="${{ runner.temp }}/nix-nario-tmp"
          mkdir -p "${TMPNIX}"
          echo "tmp=${TMPNIX}" >> $GITHUB_OUTPUT
        fi

    - id: pkg
      shell: bash
      run: |
        # Determining name, version, and hash

        if [[ -n "${{ inputs.path }}" ]]; then

          path=$(nix eval --inputs-from . --raw "${{ inputs.path }}")

          if nix store ls "${path}" &> /dev/null; then
            echo "Package already in store, skipping restore."
            echo "exists=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          file=$(basename "${path}")

          name=$(nix eval --inputs-from . --raw "${{ inputs.path }}.pname" 2> /dev/null || nix eval --inputs-from . --raw "${{ inputs.path }}.name")
          version=$(nix eval --inputs-from . --raw "${{ inputs.path }}.version" 2> /dev/null || echo "")
          hash="${file%%-*}"

        else

          if nix store ls "$(nix flake archive --json --dry-run 2> /dev/null | jq -r '.path')" &> /dev/null; then
            echo "Flake already in store, skipping restore."
            echo "exists=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          name="flake"
          hash="${{ hashFiles('**/flake.lock') }}"

        fi

        echo "name: ${name}"
        echo "name=${name}" >> $GITHUB_OUTPUT

        echo "hash: ${hash}"
        echo "hash=${hash}" >> $GITHUB_OUTPUT

        if [[ -n "${version}" ]]; then
          echo "version: ${version}"
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "key=nix-${name}-${version}-${hash}" >> $GITHUB_OUTPUT
        else
          echo "version: n/a"
          echo "version=0.0.0" >> $GITHUB_OUTPUT
          echo "key=nix-${name}-${hash}" >> $GITHUB_OUTPUT
        fi

    - id: cache
      if: ${{ steps.pkg.outputs.exists != 'true' }}
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: "${{ steps.env.outputs.tmp }}/${{ steps.pkg.outputs.name }}.nario"
        key: "${{ steps.pkg.outputs.key }}"
        restore-keys: |
          nix-${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}
          nix-${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.hash }}
          nix-${{ steps.pkg.outputs.name }}

    - if: ${{ steps.cache.outputs.cache-hit != '' }}
      shell: bash
      run: |
        # Importing ${{ steps.pkg.outputs.name }} from cache

        nix nario import --no-check-sigs < "${{ steps.env.outputs.tmp }}/${{ steps.pkg.outputs.name }}.nario"
        sudo rm -rf "${{ steps.env.outputs.tmp }}" || true
