name: nix nario restore
description: Restore the nix store to the actions cache using nix nario

inputs:
  path:
    description: "nix path to save to the cache"
    required: false

outputs:
  cache-hit:
    description: "whether the cache was hit"
    value: ${{ steps.pkg.outputs.exists || steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - id: pkg
      shell: bash
      run: |
        # Determine hash, version, and name

        if [[ -n "${{ inputs.path }}" ]]; then

          if nix store ls "$(nix eval --inputs-from . --raw "${{ inputs.path }}")" &> /dev/null; then
            echo "Package already in store, skipping restore."
            echo "exists=true" >> $GITHUB_OUTPUT
            return 0
          fi

          info=$(nix path-info --json --json-format 2 --inputs-from . "${{ inputs.path }}")
          sha256=$(echo "${info}" | jq -r '.info | to_entries | first | .value.narHash')

          hash=$(nix hash convert --to base64 "${sha256}")
          version=$(nix eval --inputs-from . --raw "${{ inputs.path }}.version" 2> /dev/null || echo "0")
          name=$(nix eval --inputs-from . --raw "${{ inputs.path }}.pname" 2> /dev/null || nix eval --inputs-from . --raw "${{ inputs.path }}.name")

        else

          if nix store ls "$(nix flake archive --json --dry-run | jq -r .path)" &> /dev/null; then
            echo "Flake already in store, skipping restore."
            echo "exists=true" >> $GITHUB_OUTPUT
            return 0
          fi

          hash=$(nix flake metadata --json | jq -r .locked.rev)
          version="0"
          name="flake"

        fi

        echo "hash=${hash}" >> $GITHUB_OUTPUT
        echo "version=${version}" >> $GITHUB_OUTPUT
        echo "name=${name}" >> $GITHUB_OUTPUT

    - id: cache
      if: ${{ steps.pkg.outputs.exists != 'true' }}
      uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"
        key: "nix-${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}-${{ steps.pkg.outputs.hash }}"
        restore-keys: |
          nix-${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}-
          nix-${{ steps.pkg.outputs.name }}-

    - if: ${{ steps.cache.outputs.cache-hit != '' }}
      shell: bash
      run: |
        # Import and clean up

        nix nario import --no-check-sigs < "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"
        rm -f "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"
