name: nix nario restore
description: Restore the nix store to the actions cache using nix nario

inputs:
  name:
    description: "name of the cache"
    required: true

  path:
    description: "nix path to save to the cache"
    required: false

outputs:
  cache-hit:
    description: "whether the cache was hit"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.path != '' }}
      shell: bash
      id: hash
      run: |
        path=$(nix eval --inputs-from . --raw "${{ inputs.path }}")
        package=$(basename "$path")
        hash="${package%%-*}"
        echo "hash=${hash}" >> $GITHUB_OUTPUT

    - uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: cache
      with:
        path: "${{ runner.temp }}/${{ inputs.name }}.nario"
        key: "nix-init-${{ inputs.name }}-${{ steps.hash.outputs.hash || hashFiles('**/flake.lock') }}"

    - if: ${{ steps.cache.outputs.cache-hit == 'true' }}
      shell: bash
      run: nix nario import --no-check-sigs < "${{ runner.temp }}/${{ inputs.name }}.nario"
