name: nix nario save
description: Save the nix store to the actions cache using nix nario

inputs:
  name:
    description: "name of the cache"
    required: true
  path:
    description: "nix path to save to the cache"
    required: false

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.path == '' }}
      shell: bash
      run: nix nario export --format 2 --all > "${{ runner.temp }}/${{ inputs.name }}.nario"

    - if: ${{ inputs.path != '' }}
      shell: bash
      run: |
        nix build --inputs-from . "${{ inputs.path }}"
        nix nario export --format 2 --inputs-from . -r "${{ inputs.path }}" > "${{ runner.temp }}/${{ inputs.name }}.nario"

    - id: pkg
      if: ${{ inputs.path != '' }}
      shell: bash
      run: |
        path=$(nix eval --inputs-from . --raw "${{ inputs.path }}")
        name=$(basename "${path}")
        hash="${name%%-*}"
        echo "hash=${hash}" >> $GITHUB_OUTPUT

    - uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: "${{ runner.temp }}/${{ inputs.name }}.nario"
        key: "nix-init-${{ inputs.name }}-${{ steps.pkg.outputs.hash || hashFiles('**/flake.lock') }}"
