name: nix nario save
description: Save the nix store to the actions cache using nix nario

inputs:
  name:
    description: "name of the cache"
    required: true

  path:
    description: "nix path to save to the cache"
    required: false

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.path == '' }}
      shell: bash
      run: nix nario export --format 2 --all > "${{ runner.temp }}/${{ inputs.name }}.nario"

    - if: ${{ inputs.path != '' }}
      shell: bash
      run: |
        nix build --inputs-from . "${{ inputs.path }}"
        nix nario export --format 2 --inputs-from . -r "${{ inputs.path }}" > "${{ runner.temp }}/${{ inputs.name }}.nario"

    - if: ${{ inputs.path != '' }}
      shell: bash
      id: hash
      run: |
        path=$(nix eval --inputs-from . --raw "${{ inputs.path }}")
        package=$(basename "$path")
        hash="${package%%-*}"
        echo "hash=${hash}" >> $GITHUB_OUTPUT

    - uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: "${{ runner.temp }}/${{ inputs.name }}.nario"
        key: "nix-init-${{ inputs.name }}-${{ steps.hash.outputs.hash || hashFiles('**/flake.lock') }}"
