name: nix nario save
description: Save the nix store to the actions cache using nix nario

inputs:
  path:
    description: "nix path to save to the cache"
    required: false

runs:
  using: "composite"
  steps:
    - id: pkg
      shell: bash
      run: |
        if [[ -n "${{ inputs.path }}" ]]; then
          path=$(nix eval --inputs-from . --raw "${{ inputs.path }}")
          file=$(basename "${path}")
          hash="${file%%-*}"
          name="${file#*-}"
        else
          hash="${{ hashFiles('**/flake.lock') }}"
          name="flake"
        fi

        echo "hash=${hash}" >> $GITHUB_OUTPUT
        echo "name=${name}" >> $GITHUB_OUTPUT

    - if: ${{ inputs.path != '' }}
      shell: bash
      run: |
        nix build --inputs-from . "${{ inputs.path }}"
        nix nario export --format 2 --inputs-from . -r "${{ inputs.path }}" > "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"

    - if: ${{ inputs.path == '' }}
      shell: bash
      run: |
        nix nario export --format 2 --all > "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"

    - uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"
        key: "nix-${{ steps.pkg.outputs.hash }}"
