name: nix nario save
description: Save the nix store to the actions cache using nix nario

inputs:
  path:
    description: "nix path to save to the cache"
    required: false

runs:
  using: "composite"
  steps:
    - id: env
      shell: bash
      run: |
        # Setup env

        TMPNIX="/nix/_tmp"
        if sudo mkdir -p "${TMPNIX}"; then
          sudo chmod 1777 "${TMPNIX}"
          echo "tmp=${TMPNIX}" >> $GITHUB_OUTPUT
        else
          echo "tmp=${{ runner.temp }}" >> $GITHUB_OUTPUT
        fi

    - id: pkg
      shell: bash
      run: |
        # Determining name, version and hash

        if [[ -n "${{ inputs.path }}" ]]; then

          path=$(nix eval --inputs-from . --raw "${{ inputs.path }}")
          file=$(basename "${path}")

          name=$(nix eval --inputs-from . --raw "${{ inputs.path }}.pname" 2> /dev/null || nix eval --inputs-from . --raw "${{ inputs.path }}.name")
          version=$(nix eval --inputs-from . --raw "${{ inputs.path }}.version" 2> /dev/null || echo "")
          hash="${file%%-*}"

        else

          name="flake"
          hash="${{ hashFiles('**/flake.lock') }}"

        fi

        echo "name: ${name}"
        echo "name=${name}" >> $GITHUB_OUTPUT

        echo "hash: ${hash}"
        echo "hash=${hash}" >> $GITHUB_OUTPUT

        if [[ -n "${version}" ]]; then
          echo "version: ${version}"
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "key=nix-${name}-${version}-${hash}" >> $GITHUB_OUTPUT
        else
          echo "version: n/a"
          echo "version=0.0.0" >> $GITHUB_OUTPUT
          echo "key=nix-${name}-${hash}" >> $GITHUB_OUTPUT
        fi

    - if: ${{ inputs.path != '' }}
      shell: bash
      run: |
        # Building and exporting ${{ steps.pkg.outputs.name }} (${{ inputs.path }})

        nix build --inputs-from . "${{ inputs.path }}"
        nix nario export --format 2 --inputs-from . -r "${{ inputs.path }}" > "${{ steps.env.outputs.tmp }}/${{ steps.pkg.outputs.name }}.nario"

    - if: ${{ inputs.path == '' }}
      shell: bash
      run: |
        # Exporting flake inputs

        inputs=()
        while IFS=$'\n' read -r input; do
            inputs+=("${input}")
        done < <(nix flake archive --json | jq -r '.inputs.[].path')

        nix nario export --format 2 --inputs-from . -r "${inputs[@]}" > "${{ steps.env.outputs.tmp }}/${{ steps.pkg.outputs.name }}.nario"

    - uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: "${{ steps.env.outputs.tmp }}/${{ steps.pkg.outputs.name }}.nario"
        key: "${{ steps.pkg.outputs.key }}"

    - shell: bash
      run: |
        # Cleaning up ${{ steps.pkg.outputs.name }}

        rm -f "${{ steps.env.outputs.tmp }}/${{ steps.pkg.outputs.name }}.nario"
