name: nix nario save
description: Save the nix store to the actions cache using nix nario

inputs:
  path:
    description: "nix path to save to the cache"
    required: false

runs:
  using: "composite"
  steps:
    - id: pkg
      shell: bash
      run: |
        # Determine hash, version, and name

        if [[ -n "${{ inputs.path }}" ]]; then

          path=$(nix eval --inputs-from . --raw "${{ inputs.path }}")
          file=$(basename "${path}")

          name=$(nix eval --inputs-from . --raw "${{ inputs.path }}.pname" 2> /dev/null || nix eval --inputs-from . --raw "${{ inputs.path }}.name")
          version=$(nix eval --inputs-from . --raw "${{ inputs.path }}.version" 2> /dev/null || echo "")
          hash="${file%%-*}"

        else

          name="flake"
          hash="${{ hashFiles('**/flake.lock') }}"

        fi

        echo "name=${name}" >> $GITHUB_OUTPUT
        echo "version=${version}" >> $GITHUB_OUTPUT
        echo "hash=${hash}" >> $GITHUB_OUTPUT

        if [[ -n "${version}" ]]; then
          echo "key=nix-${name}-${version}-${hash}" >> $GITHUB_OUTPUT
        else
          echo "key=nix-${name}-${hash}" >> $GITHUB_OUTPUT
        fi

    - if: ${{ inputs.path != '' }}
      shell: bash
      run: |
        # Build and export the package

        nix build --inputs-from . "${{ inputs.path }}"
        nix nario export --format 2 --inputs-from . -r "${{ inputs.path }}" > "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"

    - if: ${{ inputs.path == '' }}
      shell: bash
      run: |
        # Build and export the flake

        inputs=()
        while IFS=$'\n' read -r input; do
            inputs+=("${input}")
        done < <(nix flake archive --json | jq -r '.inputs.[].path')

        nix nario export --format 2 --inputs-from . -r "${inputs[@]}" > "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"

    - uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"
        key: "${{ steps.pkg.outputs.key }}"

    - shell: bash
      run: |
        # Clean up

        rm -f "${{ runner.temp }}/${{ steps.pkg.outputs.name }}.nario"
