name: update

on:
  schedule:
    - cron: "0 9 * * *" # every day at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: spotdemo4/better-checkout@347527b6a5b1c1dba59ad3b66f68b9b0835cb740 # v0.8.0
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Renovate
        uses: renovatebot/github-action@3633cede7d4d4598438e654eac4a695e46004420 # v46.1.7
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.checkout.outputs.token }}
